# Generated by Django 4.0.6 on 2022-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedFriendshipsBAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=15)),
                ('count_1', models.IntegerField()),
                ('count_2', models.IntegerField()),
                ('count_3', models.IntegerField()),
                ('count_4', models.IntegerField()),
                ('count_5', models.IntegerField()),
                ('count_6', models.IntegerField()),
                ('count_7', models.IntegerField()),
                ('count_8', models.IntegerField()),
                ('count_9', models.IntegerField()),
                ('count_10', models.IntegerField()),
                ('count_11', models.IntegerField()),
                ('count_12', models.IntegerField()),
                ('count_13', models.IntegerField()),
                ('count_14', models.IntegerField()),
                ('count_15', models.IntegerField()),
                ('count_16', models.IntegerField()),
                ('count_17', models.IntegerField()),
                ('count_18', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectedFriendshipsIRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=15)),
                ('friendships_count', models.IntegerField()),
            ],
        ),
    ]
