# Generated by Django 4.0.6 on 2022-07-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedfriendshipsirt',
            name='color',
            field=models.CharField(default='ssss', max_length=10),
            preserve_default=False,
        ),
    ]
