# Generated by Django 4.0.6 on 2022-07-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statistics', '0002_collectedfriendshipsirt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedfriendshipsirt',
            name='cardholder_name',
            field=models.CharField(default='pizza', max_length=40),
            preserve_default=False,
        ),
    ]
